project_id = "zyfbxzjfpncxfawthsht"

[functions.admin-update-email]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.pagbank-session]
verify_jwt = true

[functions.pagbank-payment-card]
verify_jwt = true

[functions.delete-user-data]
verify_jwt = false

[functions.generate-student-card]
verify_jwt = true

[functions.generate-digital-card]
verify_jwt = true
