project_id = "nwszukpenvkctthbsocw"

[functions.admin-update-email]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.pagbank-session]
verify_jwt = true

[functions.pagbank-payment-card]
verify_jwt = true
